name: Run extractData.py Quarterly
on:
  schedule:
    - cron: '0 0 1 1,4,7,10 *'
  workflow_dispatch:

jobs:
  extract_and_commit:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fredapi pandas requests yfinance

    - name: Run data extraction script
      env:
        EOD_API_KEY: ${{ secrets.EOD_API_KEY }}
        FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
      run: |
        python kiss/extractData.py

    - name: Commit and push if any changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'yasarsultan'
        git config --global user.email 'yasersultan03@gmail.com'
        git add kiss/data/*
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update data $(date + '%Y-%m-%d')" && git push)
